apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-anikersamanta-nagp-develop
  namespace: kubernetes-cluster-aniket
  labels:
    app: dotnet-nagp-app-develop
spec:
  replicas: 4
  selector:
    matchLabels:
      app: dotnet-nagp-app-develop
  template:
    metadata:
      labels:
        app: dotnet-nagp-app-develop
    spec:
      containers:
        - name: dotnet-nagp-app-develop
          image:  aniketdocker1/i-aniketsamanta-develop:latest
          env:
            - name: BRANCH_NAME
              valueFrom:
                configMapKeyRef:
                  name: configuration-variables-nagp-develop
                  key : branchName
            - name: TEXT_COLOR
              valueFrom:
                configMapKeyRef:
                  name: configuration-variables-nagp-develop
                  key : color
          imagePullPolicy: Always
          ports:
            - containerPort: 4200