apiVersion: v1
kind: Service
metadata:
  name: dotnet-nagp-app-service
spec:
  selector:
    app: nagpmasterdemo-pod
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80


