
apiVersion: v1
kind: Secret
metadata:
  name: nagp-devops-us-secret
  namespace: kubernetes-cluster-aniketsamanta
type: Opaque
data:
  username: 8j9011ert6y2i03oet5rc0yeyrgh90j
  password: r3hezm4c8ziqlmxlmbu0ady8zuuk1nd